# Generated by Django 2.2.4 on 2019-08-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190811_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='stock_actions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_balance_sheet',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_cashflow',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_financials',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_options',
            field=models.TextField(default=''),
        ),
    ]
