# Generated by Django 2.2.4 on 2019-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190812_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='stock_range_list',
            field=models.TextField(default=''),
        ),
    ]
