# Generated by Django 2.2.4 on 2019-08-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_portfolio_tickercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Tickercode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Username',
            field=models.CharField(max_length=32),
        ),
    ]
